[package]
name = "dada-tests"
description = "Integration tests of dada on image files"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[lib]
path = "common.rs"

[[test]]
name = "format_open"
path = "format_open.rs"

[[test]]
name = "tree"
path = "tree.rs"

[[test]]
name = "fragmentation"
path = "fragmentation.rs"

[dependencies]
libdada.workspace = true
rand = "0.9"
tempfile = "3.27.0"
