[package]
name = "dadactl"
description = "Inspect and manipulate dada images"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "dadactl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
libdada.workspace = true
uuid = "1.26.1"

[dev-dependencies]
tempfile = "3.27.0"
