[package]
name = "fsck-dada"
description = "Check and repair a dada filesystem"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "fsck-dada"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
libdada.workspace = true

[dev-dependencies]
rand = "0.9"
